{
  "formatVersion": "1.1",
  "component": {
    "group": "com.mao.tracecheetah",
    "module": "trace_cheetah_plugin",
    "version": "1.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "trace_cheetah_plugin-1.0.1.jar",
          "url": "trace_cheetah_plugin-1.0.1.jar",
          "size": 15884,
          "sha512": "1f3e633ed0a289439ac2f6fb943a85b384ed06e95a68c2b2cf4bf637ba95c82107ac5972b96d8116c8643a9513e3bdc2a1e17be6be2d50d5b4dfc43bbbac7aca",
          "sha256": "67d615a2b89d0cc327f073d480f117329339757835960311008c91e72db21c32",
          "sha1": "747879b15b06f5e9d4b9934ea3079f2b9cb0e3e6",
          "md5": "98fad099c9958d132b21c1856156e96f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.5.21"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "7.0.0"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.0"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "9.0"
          }
        }
      ],
      "files": [
        {
          "name": "trace_cheetah_plugin-1.0.1.jar",
          "url": "trace_cheetah_plugin-1.0.1.jar",
          "size": 15884,
          "sha512": "1f3e633ed0a289439ac2f6fb943a85b384ed06e95a68c2b2cf4bf637ba95c82107ac5972b96d8116c8643a9513e3bdc2a1e17be6be2d50d5b4dfc43bbbac7aca",
          "sha256": "67d615a2b89d0cc327f073d480f117329339757835960311008c91e72db21c32",
          "sha1": "747879b15b06f5e9d4b9934ea3079f2b9cb0e3e6",
          "md5": "98fad099c9958d132b21c1856156e96f"
        }
      ]
    }
  ]
}
