{
  "formatVersion": "1.1",
  "component": {
    "group": "com.mao.tracecheetah",
    "module": "trace_cheetah_plugin",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "trace_cheetah_plugin-1.0.0.jar",
          "url": "trace_cheetah_plugin-1.0.0.jar",
          "size": 15897,
          "sha512": "20f3c5d44c9e7f2ec2b5096bb45e8f97682c3e83bf77a4ecbc8d5482b25807a2d1c07f9a4f511d067fdfb97278895d5c3830d61cf18595836f4d429e5fcc3905",
          "sha256": "858f423f98404e33f1b9dfac5e4708fd76b6280c1d94a7482aaaf0bfbaff994b",
          "sha1": "305d8a3e8268fb4d05e1e342939d9c946902c22d",
          "md5": "df80601adc80b8af74067f41b040c51e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.5.21"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "7.0.0"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.0"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "9.0"
          }
        }
      ],
      "files": [
        {
          "name": "trace_cheetah_plugin-1.0.0.jar",
          "url": "trace_cheetah_plugin-1.0.0.jar",
          "size": 15897,
          "sha512": "20f3c5d44c9e7f2ec2b5096bb45e8f97682c3e83bf77a4ecbc8d5482b25807a2d1c07f9a4f511d067fdfb97278895d5c3830d61cf18595836f4d429e5fcc3905",
          "sha256": "858f423f98404e33f1b9dfac5e4708fd76b6280c1d94a7482aaaf0bfbaff994b",
          "sha1": "305d8a3e8268fb4d05e1e342939d9c946902c22d",
          "md5": "df80601adc80b8af74067f41b040c51e"
        }
      ]
    }
  ]
}
